### ISSUE TITLE
Presentation Web Smart Search Rebuild fails

### ISSUE THREAD

**Issue by backlash1897** [KenticoDevTrev/XperienceCommunity.Baseline#6]
Hi Trev,

Smart Search Index rebuild fails for the presentation web (it does not fail for the admin web).

The issues seems to be caused by the referenced package "RelationshipsExtended.Base" (referenced [here](https://github.com/KenticoDevTrev/XperienceCommunity.Baseline/blob/master/src/Core/Core.Library.KX13/Core.Library.KX13.csproj)) which has a global eventhandler that has a dependency on an sql table "CMS_TreeCategory".

Installing the package "RelationshipsExtended" to the CMSApp Projekt fixes the issue, but in my opinion that feature should be optional, that's why I am submitting the issue here.

Event log reads

Exception:
[DataConnection.HandleError]:

Query:
SELECT [CategoryName], cms_category.CategoryID
FROM CMS_Category INNER JOIN ON [cms_category].[categoryid] = [cms_treecategory].[categoryid]
WHERE [NodeID] = @NodeID

Caused exception:
Incorrect syntax near the keyword 'ON'.

Stack trace: at CMS.DataEngine.AbstractDataConnection.HandleError(String queryText, Exception ex)
at CMS.DataEngine.AbstractDataConnection.ExecuteReader(String queryText, QueryDataParameters queryParams, QueryTypeEnum queryType, CommandBehavior commandBehavior)
at CMS.DataEngine.GeneralConnection.ExecuteReaderCore(QueryParameters query, CommandBehavior commandBehavior)
at CMS.DataEngine.SqlExecutionHelper.ExecuteWithRetryCore[TResult](Func`1 executionFunc, Int32 retryCount, Func`2 exceptionRetryPredicate)
at CMS.DataEngine.SqlExecutionHelper.ExecuteWithDeadlockRetryInternal[TResult](Func`1 executionFunc, Int32 retryCount)
at CMS.DataEngine.DataQueryBase`1.GetReaderFromDBInternal(CommandBehavior commandBehavior, Boolean newConnection)
at CMS.DataEngine.DataQueryBase`1.GetReader(CommandBehavior commandBehavior, Boolean newConnection)
at CMS.DataEngine.DataQueryBase`1.GetReader(CommandBehavior commandBehavior, Boolean newConnection)
at CMS.DataEngine.DataQueryBase`1.GetEnumerableResult(CommandBehavior commandBehavior, Boolean newConnection)+MoveNext()
at CMS.DataEngine.DataExtensions.As[InfoType](IEnumerable`1 dataRecords, Func`2 createObjectFunc)
at RelationshipsExtended.RelationshipsExtendedLoaderModuleBase.TreeNodeCategory_GetContent_Execute(Object sender, DocumentSearchEventArgs e)
at CMS.Base.AbstractHandler.CallEventHandler[TArgs](EventHandler`1 h, TArgs e)
at CMS.Base.AbstractHandler.Raise[TArgs](String partName, List`1 list, TArgs e, Boolean important)
at CMS.Base.SimpleHandler`2.RaiseExecute(TArgs e)
at CMS.Base.SimpleHandler`2.StartEvent(TArgs e)
at CMS.DocumentEngine.SearchDocumentCreator.GetFieldContent(SearchDocument doc, ISearchField field)
at System.Collections.Generic.List`1.ForEach(Action`1 action)
at CMS.DocumentEngine.SearchDocumentCreator.Create()
at CMS.DocumentEngine.DocumentSearchIndexer.Rebuild(SearchIndexInfo indexInfo, IEnumerable`1 searchableObjects, Boolean fullRebuild)

**Comment by KenticoDevTrev** [comment]
Relationships extended is primarily an admin package with a couple MVC side helper methods, so I don't consider needing the admin installed as a bug.  That's pretty much the whole module.

If you just need an extension method only then I would just copy the extensions.  If using the baseline project, it does use this for some of it's functions which hopefully won't be needed in Xperience by kentico. Sorry but you do need the admin, even if you don't leverage all it's features.

**Comment by KenticoDevTrev** [comment]
I am eventually working on a refactor of the baseline, I'll see if I can split the relationships extended to the items that need it only, the core may not but some do
